language: python
python:
  - "2.6"
env:
  global:
    - foo=bar 
  matrix:
    - TESTFOLDER=test/agent1 
    - TESTFOLDER=test/agent2
install:
  - "pip install coverage"
  - git clone https://github.com/boto/botocore.git && cd botocore && python setup.py install
  - git clone https://github.com/boto/boto3.git && cd boto3 && python setup.py install
script:
  - echo ${foo}
  - cd ${TRAVIS_BUILD_DIR}
  - $TESTFOLDER/unittest.sh
  - ./build.sh ./
deploy :
  provider: s3
  access_key_id: ${access_key_id}
  secret_access_key: ${secret_access_key}
  region: "us-west-2"
  bucket: "test.tmwrs"
  skip_cleanup: true
  local_dir: ptn
  upload-dir: travis-builds
notifications:
  slack: peter-travis:YRV9bI0k8VV7oAtkEpCZ7pjI
